import numpy as np
import matplotlib.pyplot as plt
import math

t = np.arange(0, 110.77, 0.01)
gap = 10
error_std = t - t
dp = np.loadtxt('/home/robot/robot/roake_param_identify/build/drag/drag_data/hat_p.txt')

p_pd = np.loadtxt('/home/robot/robot/roake_param_identify/build/drag/PD_error/position_ly.txt')
ep_pd = np.loadtxt('/home/robot/robot/roake_param_identify/build/drag/PD_error/position_error_ly.txt')

p = np.loadtxt('/home/robot/robot/roake_param_identify/build/drag/simulation_6/position_ly.txt')
ep = np.loadtxt('/home/robot/robot/roake_param_identify/build/drag/simulation_6/position_error_ly.txt')

# p_pd = np.loadtxt('/home/robot/robot/roake_param_identify/build/ly_data/SGPR/PD/position_ly.txt')
# ep_pd = np.loadtxt('/home/robot/robot/roake_param_identify/build/ly_data/SGPR/PD/position_error_ly.txt')

# p = np.loadtxt('/home/robot/robot/roake_param_identify/build/ly_data/SGPR/s1/position_ly.txt')
# ep = np.loadtxt('/home/robot/robot/roake_param_identify/build/ly_data/SGPR/s1/position_error_ly.txt')

plt.subplot(4,2,1)
plt.plot(dp[:,0], c='green',label='$dp_1$')
plt.plot(p_pd[:,0], c='purple',label='$p_{pd1}$')
plt.plot(p[:,0], c='red',label='$p_1$')
plt.ylabel('angle/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,2)
plt.plot(dp[:,1], c='green',label='$dp_1$')
plt.plot(p_pd[:,1], c='purple',label='$p_{pd2}$')
plt.plot(p[:,1], c='red',label='$p_2$')
plt.ylabel('angle/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,3)
plt.plot(dp[:,2], c='green',label='$dp_1$')
plt.plot(p_pd[:,2], c='purple',label='$p_{pd3}$')
plt.plot(p[:,2], c='red',label='$p_3$')
plt.ylabel('angle/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,4)
plt.plot(dp[:,3], c='green',label='$dp_1$')
plt.plot(p_pd[:,3], c='purple',label='$p_{pd4}$')
plt.plot(p[:,3], c='red',label='$p_4$')
plt.ylabel('angle/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,5)
plt.plot(dp[:,4], c='green',label='$dp_1$')
plt.plot(p_pd[:,4], c='purple',label='$p_{pd5}$')
plt.plot(p[:,4], c='red',label='$p_5$')
plt.ylabel('angle/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,6)
plt.plot(dp[:,5], c='green',label='$dp_1$')
plt.plot(p_pd[:,5], c='purple',label='$p_{pd6}$')
plt.plot(p[:,5], c='red',label='$p_6$')
plt.ylabel('angle/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,7)
plt.plot(dp[:,6], c='green',label='$dp_1$')
plt.plot(p_pd[:,6], c='purple',label='$p_{pd7}$')
plt.plot(p[:,6], c='red',label='$p_7$')
plt.ylabel('angle/rad')
plt.xlabel('steps')
plt.legend()
plt.show()

plt.subplot(4,2,1)
plt.plot(ep_pd[:,0], c='cyan',label='$ep_{pd1}$')
plt.plot(ep[:,0], c='blue',label='$ep_1$')
plt.plot(error_std, c='red')
plt.ylabel('error/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,2)
plt.plot(ep_pd[:,1], c='cyan',label='$ep_{pd2}$')
plt.plot(ep[:,1], c='blue',label='$ep_2$')
plt.plot(error_std, c='red')
plt.ylabel('error/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,3)
plt.plot(ep_pd[:,2], c='cyan',label='$ep_{pd3}$')
plt.plot(ep[:,2], c='blue',label='$ep_3$')
plt.plot(error_std, c='red')
plt.ylabel('error/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,4)
plt.plot(ep_pd[:,3], c='cyan',label='$ep_{pd4}$')
plt.plot(ep[:,3], c='blue',label='$ep_4$')
plt.plot(error_std, c='red')
plt.ylabel('error/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,5)
plt.plot(ep_pd[:,4], c='cyan',label='$ep_{pd5}$')
plt.plot(ep[:,4], c='blue',label='$ep_5$')
plt.plot(error_std, c='red')
plt.ylabel('error/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,6)
plt.plot(ep_pd[:,5], c='cyan',label='$ep_{pd6}$')
plt.plot(ep[:,5], c='blue',label='$ep_6$')
plt.plot(error_std, c='red')
plt.ylabel('error/rad')
plt.xlabel('steps')
plt.legend()
plt.subplot(4,2,7)
plt.plot(ep_pd[:,6], c='cyan',label='$ep_{pd7}$')
plt.plot(ep[:,6], c='blue',label='$ep_7$')
plt.plot(error_std, c='red')
plt.ylabel('error/rad')
plt.xlabel('steps')
plt.legend()
plt.show()

# plt.subplot(4,2,1)
# plt.plot(ep[:,0], color=(241/255, 64/255, 64/255),label='$ep_{SGPR1}$')
# plt.plot(ep_pd[:,0], color=(26/255, 111/255, 223/255),label='$ep_{pd1}$')
# plt.plot(error_std, c='gray')
# plt.ylabel('error/rad')
# # plt.xlabel('steps')
# plt.legend()
# plt.subplot(4,2,2)
# plt.plot(ep[:,1], color=(241/255, 64/255, 64/255),label='$ep_{SGPR2}$')
# plt.plot(ep_pd[:,1], color=(26/255, 111/255, 223/255),label='$ep_{pd2}$')
# plt.plot(error_std, c='gray')
# # plt.ylabel('error/rad')
# # plt.xlabel('steps')
# plt.legend()
# plt.subplot(4,2,3)
# plt.plot(ep[:,2], color=(241/255, 64/255, 64/255),label='$ep_{SGPR3}$')
# plt.plot(ep_pd[:,2], color=(26/255, 111/255, 223/255),label='$ep_{pd3}$')
# plt.plot(error_std, c='gray')
# plt.ylabel('error/rad')
# # plt.xlabel('steps')
# plt.legend()
# plt.subplot(4,2,4)
# plt.plot(ep[:,3], color=(241/255, 64/255, 64/255),label='$ep_{SGPR4}$')
# plt.plot(ep_pd[:,3], color=(26/255, 111/255, 223/255),label='$ep_{pd4}$')
# plt.plot(error_std, c='gray')
# # plt.ylabel('error/rad')
# # plt.xlabel('steps')
# plt.legend()
# plt.subplot(4,2,5)
# plt.plot(ep[:,4], color=(241/255, 64/255, 64/255),label='$ep_{SGPR5}$')
# plt.plot(ep_pd[:,4], color=(26/255, 111/255, 223/255),label='$ep_{pd5}$')
# plt.plot(error_std, c='gray')
# plt.ylabel('error/rad')
# # plt.xlabel('steps')
# plt.legend()
# plt.subplot(4,2,6)
# plt.plot(ep[:,5], color=(241/255, 64/255, 64/255),label='$ep_{SGPR6}$')
# plt.plot(ep_pd[:,5], color=(26/255, 111/255, 223/255),label='$ep_{pd6}$')
# plt.plot(error_std, c='gray')
# # plt.ylabel('error/rad')
# plt.xlabel('steps')
# plt.legend()
# plt.subplot(4,2,7)
# plt.plot(ep[:,6], color=(241/255, 64/255, 64/255),label='$ep_{SGPR7}$')
# plt.plot(ep_pd[:,6], color=(26/255, 111/255, 223/255),label='$ep_{pd7}$')
# plt.plot(error_std, c='gray')
# plt.ylabel('error/rad')
# plt.xlabel('steps')
# plt.legend()
# plt.show()
# plt.savefig("fig6", dpi=300, format="svg")



plt.figure(figsize=(12, 8))
plt.rcParams.update({'font.size':12})

plt.subplot(4,2,1)
plt.plot(ep[:,0], color=(241/255, 64/255, 64/255),label='$ep_{SGPR1}$')
plt.plot(ep_pd[:,0], color=(26/255, 111/255, 223/255),label='$ep_{pd1}$')
plt.plot(error_std, c='gray')
plt.ylabel('error/rad')
# plt.xlabel('steps')
plt.tick_params(direction='in', which='both')
plt.legend(fontsize=12, loc='upper right')

plt.subplot(4,2,2)
plt.plot(ep[:,1], color=(241/255, 64/255, 64/255),label='$ep_{SGPR2}$')
plt.plot(ep_pd[:,1], color=(26/255, 111/255, 223/255),label='$ep_{pd2}$')
plt.plot(error_std, c='gray')
# plt.ylabel('error/rad')
# plt.xlabel('steps')
plt.tick_params(direction='in', which='both')
plt.legend(fontsize=12, loc='upper right')

plt.subplot(4,2,3)
plt.plot(ep[:,2], color=(241/255, 64/255, 64/255),label='$ep_{SGPR3}$')
plt.plot(ep_pd[:,2], color=(26/255, 111/255, 223/255),label='$ep_{pd3}$')
plt.plot(error_std, c='gray')
plt.ylabel('error/rad')
# plt.xlabel('steps')
plt.tick_params(direction='in', which='both')
plt.legend(fontsize=12, loc='upper right')

plt.subplot(4,2,4)
plt.plot(ep[:,3], color=(241/255, 64/255, 64/255),label='$ep_{SGPR4}$')
plt.plot(ep_pd[:,3], color=(26/255, 111/255, 223/255),label='$ep_{pd4}$')
plt.plot(error_std, c='gray')
# plt.ylabel('error/rad')
# plt.xlabel('steps')
plt.tick_params(direction='in', which='both')
plt.legend(fontsize=12, loc='upper right')

plt.subplot(4,2,5)
plt.plot(ep[:,4], color=(241/255, 64/255, 64/255),label='$ep_{SGPR5}$')
plt.plot(ep_pd[:,4], color=(26/255, 111/255, 223/255),label='$ep_{pd5}$')
plt.plot(error_std, c='gray')
plt.ylabel('error/rad')
# plt.xlabel('steps')
plt.tick_params(direction='in', which='both')
plt.legend(fontsize=12, loc='upper right')

plt.subplot(4,2,6)
plt.plot(ep[:,5], color=(241/255, 64/255, 64/255),label='$ep_{SGPR6}$')
plt.plot(ep_pd[:,5], color=(26/255, 111/255, 223/255),label='$ep_{pd6}$')
plt.plot(error_std, c='gray')
# plt.ylabel('error/rad')
plt.xlabel('steps')
plt.tick_params(direction='in', which='both')
plt.legend(fontsize=12, loc='upper right')

plt.subplot(4,2,7)
plt.plot(ep[:,6], color=(241/255, 64/255, 64/255),label='$ep_{SGPR7}$')
plt.plot(ep_pd[:,6], color=(26/255, 111/255, 223/255),label='$ep_{pd7}$')
plt.plot(error_std, c='gray')
plt.ylabel('error/rad')
plt.xlabel('steps')
plt.tick_params(direction='in', which='both')
plt.legend(fontsize=12, loc='upper right')
plt.subplots_adjust(left=0.125, bottom=0.125, right=0.9, top=0.9, wspace=0.2, hspace=0.35)
# plt.savefig("fig6.png", dpi=800)
plt.show()

